FROM node
WORKDIR /redis-cache
RUN npm init -y
RUN npm install redis knex express pg swagger-ui-express swagger-jsdoc ioredis
COPY index.js populate.js swagger.js ./

ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_PORT
ARG POSTGRES_IP
ARG REDIS_1_IP
ARG REDIS_2_IP
ARG REDIS_3_IP
ARG REDIS_PORT
ENV POSTGRES_USER=${POSTGRES_USER} POSTGRES_PASSWORD=${POSTGRES_PASSWORD} POSTGRES_IP=${POSTGRES_IP} \
POSTGRES_PORT=${POSTGRES_PORT} REDIS_1_IP=${REDIS_1_IP} REDIS_2_IP=${REDIS_2_IP} REDIS_3_IP=${REDIS_3_IP} REDIS_PORT=${REDIS_PORT}

CMD ["node", "index"]